## Linux最基础缓冲区溢出调试两问题分析

**测试环境**

- Ubuntu 14.04 LTS - 64bit  
- gcc version: 4.8.4  
- Linux Kernel version: 3.13.0

**测试代码**

{% highlight c %}
// test.c
#include <string.h>

int main(int  argc, char **argv)
{
    char array[512];
    if(argc > 1){
        strcpy(array, argv[1]);
    }
    return 0;
}
{% endhighlight %}

**编译命令**

- 编译为 32 位程序
- 关闭栈不可执行保护
- 关闭 canary 保护

```
gcc -o test test.c -m32 -z execstack -fno-stack-protector
```

**关闭ASLR保护**

```
sudo echo 0 > /proc/sys/kernel/randomize_va_space
```

**关闭core dump限制**

```
ulimit -c unlimited
```

**问题（1）**

刚开始用

```
./test $(./python -c "print('A' * 516 + 'BBBB')")
```

寻找覆盖返回地址的偏移量，就是通过把 'A' 的数量每次加减 4 来使 BBBB 覆盖返回地址。问题是：在 516 个 'A' 时不会产生 Segment fault ， 520 个 'A' 时第一次产生 Segment fault ，这时候 gdb 查看 core dump ，发现返回地址并不是我想要的 'BBBB' ，而是和 'B' 的 ASCII 看起来没有联系的一个地址。在使用 524 个 'A' 时 gdb 查看 core dump 才正确地使返回地址被覆盖为 'BBBB' 。

![]({{ site.url }}/images/207/3.png)

![]({{ site.url }}/images/207/4.png)

**解决**

又使用GDB跟踪了一遍程序执行：

在520个A时首次出现段错误：

![]({{ site.url }}/images/207/1.png)

这个时候查看 core ，发现并没有覆盖掉返回地址，我之前理解错的地方就是这里，这个时候的段错误并不是发生在 main 函数向 \__libc_start_main 返回的时候：

![]({{ site.url }}/images/207/2.png)

由于返回地址并没有被覆盖，所以正常返回到了 \__libc_start_main ，段错误是由于在返回到 \__libc_start_main 后的第三条指令：

![]({{ site.url }}/images/207/x1.png)

之后 $esi 变成了：

![]({{ site.url }}/images/207/x2.png)

再往下有一条 call 指令：

![]({{ site.url }}/images/207/x3.png)

真正的段错误是这里引发的。

**问题（2）**

在已经 `ulimit -c unlimited` 的情况下，使用（1）中的 'A' 和 'B' 结合的方法在产生 Segment fault 时会产生 core dump ，然而在使用具体的 shellcode 导致 Segment fault 时不会产生 core dump 。

![]({{ site.url }}/images/207/t1.png)

**解决**

参考我的另一篇++讲解 core 的文章，本问题发生的具体原因还未查明。